---
:aws_access_key_id: Your AWS_ACCESS_KEY_ID
:aws_secret_access_key: Your AWS_SECRET_ACCESS_KEY
:instance_type: t2.micro
:ssm_role: "IAM Role used by SSM"
:command_timeout: 18000
:region_data:
- :region: ap-south-1
  :ami_id: ami-995c23f6
  :key: mumbai-loadtesting
  :node_count: 3
  :subnet_id: subnet-abcd1234
  :commands:
  - 'ab -r -s 300 -c 10 -n 100 "http://example.com/"'
- :region: us-east-1
  :ami_id: ami-34193d22
  :key: loadtesting
  :node_count: 2
  :subnet_id: subnet-abcd7890
  :commands:
  - 'ab -r -s 300 -c 10 -n 100 "http://example.com/" && ab -r -s 300 -c 10 -n 100 "http://example.com/new_url"'
